// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ14ZiKS5VyMKLU_zGWVUTjlIcfEKuQ9g',
    appId: '1:38438709669:android:e311d076c0e13ac47e604c',
    messagingSenderId: '38438709669',
    projectId: 'parcel-659eb',
    databaseURL: 'https://parcel-659eb-default-rtdb.firebaseio.com',
    storageBucket: 'parcel-659eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisQpKYtHX4toeTpzrhgq8c8zxtvTfTyI',
    appId: '1:38438709669:ios:5e20905628647fb77e604c',
    messagingSenderId: '38438709669',
    projectId: 'parcel-659eb',
    databaseURL: 'https://parcel-659eb-default-rtdb.firebaseio.com',
    storageBucket: 'parcel-659eb.firebasestorage.app',
    iosBundleId: 'com.example.secureDrop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOXeX2q2JeRsZyfxhQofI12La-VWqeY7w',
    appId: '1:38438709669:web:74ec719cd3c68f767e604c',
    messagingSenderId: '38438709669',
    projectId: 'parcel-659eb',
    authDomain: 'parcel-659eb.firebaseapp.com',
    databaseURL: 'https://parcel-659eb-default-rtdb.firebaseio.com',
    storageBucket: 'parcel-659eb.firebasestorage.app',
    measurementId: 'G-PK72T6V7F6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOXeX2q2JeRsZyfxhQofI12La-VWqeY7w',
    appId: '1:38438709669:web:fbb44e3fb09297a67e604c',
    messagingSenderId: '38438709669',
    projectId: 'parcel-659eb',
    authDomain: 'parcel-659eb.firebaseapp.com',
    databaseURL: 'https://parcel-659eb-default-rtdb.firebaseio.com',
    storageBucket: 'parcel-659eb.firebasestorage.app',
    measurementId: 'G-KC1GMTD1CP',
  );

}